<?= $this->extend('layout') ?>

<?= $this->section('title') ?>Reports Dashboard<?= $this->endSection() ?>

<?= $this->section('content') ?>

<div class="container mt-4">
    <h3>Reports Dashboard</h3>

    <!-- Summary Cards -->
    <div class="row g-3 mb-3">
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">Total Sales</div>
                <div class="stat-value">₱ 120,500</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">Orders</div>
                <div class="stat-value">240</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">New Customers</div>
                <div class="stat-value">35</div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">Top Product</div>
                <div class="stat-value">Milk Tea</div>
            </div>
        </div>
    </div>

    <!-- Sales Trend Chart -->
    <div class="page-card">
        <h5>📈 Sales Trend (Last 7 Days)</h5>
        <canvas id="salesChart" height="100"></canvas>
    </div>

    <!-- Top Products Bar Chart -->
    <div class="page-card">
        <h5>🏆 Top 5 Best-Selling Products</h5>
        <canvas id="topProductsChart" height="100"></canvas>
    </div>

    <!-- Reports Table -->
    <div class="page-card">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0">Recent Reports</h5>
            <button class="btn btn-primary">📥 Download Report</button>
        </div>

        <table class="table table-bordered table-striped">
            <thead class="table-dark">
                <tr>
                    <th>Report</th>
                    <th>Date</th>
                    <th>Generated By</th>
                    <th>Status</th>
                    <th style="width: 150px;">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Monthly Sales Report</td>
                    <td>Sept 15, 2025</td>
                    <td>Admin</td>
                    <td><span class="badge bg-success">Completed</span></td>
                    <td>
                        <button class="btn btn-sm btn-outline-primary">View</button>
                        <button class="btn btn-sm btn-outline-secondary">Download</button>
                    </td>
                </tr>
                <tr>
                    <td>Inventory Summary</td>
                    <td>Sept 10, 2025</td>
                    <td>Admin</td>
                    <td><span class="badge bg-warning">Pending</span></td>
                    <td>
                        <button class="btn btn-sm btn-outline-primary">View</button>
                        <button class="btn btn-sm btn-outline-secondary">Download</button>
                    </td>
                </tr>
                <tr>
                    <td>Customer Feedback Analysis</td>
                    <td>Sept 01, 2025</td>
                    <td>Manager</td>
                    <td><span class="badge bg-success">Completed</span></td>
                    <td>
                        <button class="btn btn-sm btn-outline-primary">View</button>
                        <button class="btn btn-sm btn-outline-secondary">Download</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- Notes Section -->
    <div class="page-card">
        <h5>Notes</h5>
        <p>Generate reports weekly to monitor sales trends and inventory health. Use charts to identify seasonal patterns and top-performing products.</p>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Sales Trend Line Chart
    const salesCtx = document.getElementById('salesChart');
    new Chart(salesCtx, {
        type: 'line',
        data: {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            datasets: [{
                label: 'Sales (₱)',
                data: [15000, 12000, 18000, 22000, 25000, 30000, 28000],
                borderColor: '#007bff',
                backgroundColor: 'rgba(0, 123, 255, 0.1)',
                fill: true,
                tension: 0.4,
                borderWidth: 2
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { display: false }
            },
            scales: {
                y: { beginAtZero: true }
            }
        }
    });

    // Top Products Bar Chart
    const productsCtx = document.getElementById('topProductsChart');
    new Chart(productsCtx, {
        type: 'bar',
        data: {
            labels: ['Milk Tea', 'Fries', 'Burger', 'Pizza', 'Iced Coffee'],
            datasets: [{
                label: 'Units Sold',
                data: [120, 90, 75, 65, 55],
                backgroundColor: ['#007bff', '#28a745', '#ffc107', '#dc3545', '#6f42c1']
            }]
        },
        options: {
            responsive: true,
            scales: {
                y: { beginAtZero: true }
            }
        }
    });
</script>

<style>
    body {
        background: #f8fbff;
    }
    .page-card {
        background: white;
        border-radius: 15px;
        padding: 20px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        margin-bottom: 20px;
    }
    .stat-card {
        text-align: center;
        padding: 20px;
        border-radius: 12px;
        background: #ffffff;
        box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        transition: 0.3s;
    }
    .stat-card:hover {
        transform: translateY(-3px);
        box-shadow: 0 6px 14px rgba(0,0,0,0.12);
    }
    .stat-title {
        font-size: 0.9rem;
        font-weight: 600;
        color: #555;
    }
    .stat-value {
        font-size: 1.6rem;
        font-weight: bold;
        margin-top: 5px;
    }
</style>

<?= $this->endSection() ?>
