<?= $this->extend('layout') ?>

<?= $this->section('title') ?>Reports Dashboard<?= $this->endSection() ?>

<?= $this->section('content') ?>

<div class="container mt-4">
    <h3>Reports Dashboard</h3>

    <!-- Summary Cards -->
    <div class="row g-3 mb-3">
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">Total Sales</div>
                <div class="stat-value">₱ <?= number_format($totalSales ?? 0, 2) ?></div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">Orders</div>
                <div class="stat-value"><?= $totalOrders ?? 0 ?></div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">New Customers</div>
                <div class="stat-value"><?= $newCustomers ?? 0 ?></div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="stat-card">
                <div class="stat-title">Top Product</div>
                <div class="stat-value"><?= esc($topProduct ?? 'N/A') ?></div>
            </div>
        </div>
    </div>

    <!-- Sales Trend Chart -->
    <div class="page-card">
        <h5>📈 Sales Trend (Last 7 Days)</h5>
        <canvas id="salesChart" height="100"></canvas>
    </div>

    <!-- Top Products Bar Chart -->
    <div class="page-card">
        <h5>🏆 Top 5 Best-Selling Products</h5>
        <canvas id="topProductsChart" height="100"></canvas>
    </div>

    <!-- Reports Table -->
    <div class="page-card">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0">Recent Reports</h5>
            <button class="btn btn-primary" onclick="generateReport()">📥 Generate Report</button>
        </div>

        <table class="table table-bordered table-striped">
            <thead class="table-dark">
                <tr>
                    <th>Report</th>
                    <th>Date</th>
                    <th>Generated By</th>
                    <th>Status</th>
                    <th style="width: 150px;">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if (!empty($recentReports)): ?>
                    <?php foreach ($recentReports as $report): ?>
                        <tr>
                            <td>Order Report - <?= esc($report['item_name']) ?></td>
                            <td><?= $report['order_date'] ? date('M d, Y', strtotime($report['order_date'])) : 'N/A' ?></td>
                            <td><?= esc($report['generated_by'] ?? 'System') ?></td>
                            <td>
                                <span class="badge 
                                    <?php 
                                    $status = $report['status'];
                                    if ($status === 'delivered') echo 'bg-success';
                                    elseif ($status === 'confirmed') echo 'bg-info';
                                    else echo 'bg-warning';
                                    ?>">
                                    <?= ucfirst(str_replace('_', ' ', $status)) ?>
                                </span>
                            </td>
                            <td>
                                <button class="btn btn-sm btn-outline-primary" onclick="viewReport(<?= $report['id'] ?>)">View</button>
                                <button class="btn btn-sm btn-outline-secondary" onclick="downloadReport(<?= $report['id'] ?>)">Download</button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5" class="text-center text-muted">No reports available yet.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>

    <!-- Notes Section -->
    <div class="page-card">
        <h5>Notes</h5>
        <p>Generate reports weekly to monitor sales trends and inventory health. Use charts to identify seasonal patterns and top-performing products.</p>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Sales Trend Line Chart
    const salesCtx = document.getElementById('salesChart');
    const salesData = <?= json_encode($salesTrend ?? []) ?>;
    const salesLabels = salesData.map(item => item.day);
    const salesValues = salesData.map(item => item.sales);
    
    new Chart(salesCtx, {
        type: 'line',
        data: {
            labels: salesLabels,
            datasets: [{
                label: 'Sales (₱)',
                data: salesValues,
                borderColor: '#007bff',
                backgroundColor: 'rgba(0, 123, 255, 0.1)',
                fill: true,
                tension: 0.4,
                borderWidth: 2
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { display: false }
            },
            scales: {
                y: { 
                    beginAtZero: true,
                    ticks: {
                        callback: function(value) {
                            return '₱' + value.toLocaleString();
                        }
                    }
                }
            }
        }
    });

    // Top Products Bar Chart
    const productsCtx = document.getElementById('topProductsChart');
    const topProductsData = <?= json_encode($topProducts ?? []) ?>;
    const productLabels = topProductsData.map(item => item.item_name);
    const productQuantities = topProductsData.map(item => parseInt(item.total_quantity));
    const colors = ['#007bff', '#28a745', '#ffc107', '#dc3545', '#6f42c1'];
    
    new Chart(productsCtx, {
        type: 'bar',
        data: {
            labels: productLabels.length > 0 ? productLabels : ['No Data'],
            datasets: [{
                label: 'Units Sold',
                data: productQuantities.length > 0 ? productQuantities : [0],
                backgroundColor: productLabels.length > 0 ? colors.slice(0, productLabels.length) : colors[0]
            }]
        },
        options: {
            responsive: true,
            scales: {
                y: { beginAtZero: true }
            }
        }
    });
</script>

<style>
    body {
        background: #f8fbff;
    }
    .page-card {
        background: white;
        border-radius: 15px;
        padding: 20px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        margin-bottom: 20px;
    }
    .stat-card {
        text-align: center;
        padding: 20px;
        border-radius: 12px;
        background: #ffffff;
        box-shadow: 0 4px 12px rgba(0,0,0,0.08);
        transition: 0.3s;
    }
    .stat-card:hover {
        transform: translateY(-3px);
        box-shadow: 0 6px 14px rgba(0,0,0,0.12);
    }
    .stat-title {
        font-size: 0.9rem;
        font-weight: 600;
        color: #555;
    }
    .stat-value {
        font-size: 1.6rem;
        font-weight: bold;
        margin-top: 5px;
    }
</style>

<script>
    function viewReport(reportId) {
        // Implement view report functionality
        alert('Viewing report #' + reportId);
        // You can redirect to a detailed report page or show a modal
    }

    function downloadReport(reportId) {
        // Implement download report functionality
        alert('Downloading report #' + reportId);
        // You can create a PDF or CSV export here
    }

    function generateReport() {
        // Implement generate report functionality
        if (confirm('Generate a new comprehensive report?')) {
            // You can redirect to a report generation page or trigger an AJAX call
            window.location.href = '<?= base_url("Central_AD/reports") ?>?generate=1';
        }
    }
</script>

<?= $this->endSection() ?>
